Repository turbot/terraform-provider-turbot, pull requests merged in 2020-07, with the labels that each got.

#40 [BUG]:turbot_mod resource always plans an update to current_version
  turbot/resource_turbot_mod.go
Labels: bug, size/XS

#31 Update the create resource code
  website/docs/r/resource.html.markdown
Labels: documentation, size/XS

#29 Fix the bulleted list
  website/docs/r/shadow_resource.html.markdown
Labels: documentation, size/XS

#30 Update the create resource script
  website/docs/r/smart_folder_attachment.html.markdown
Labels: documentation, size/XS

#41 [BUG]Fix read operations to support tags
  .travis.yml
  apiClient/saml_directory.go
  apiClient/turbot_directory.go
  apiClient/types.go
  turbot/data_source_turbot_resource.go
  turbot/data_source_turbot_resource_test.go
  turbot/resource_turbot_folder.go
  turbot/resource_turbot_google_directory.go
  turbot/resource_turbot_local_directory.go
  turbot/resource_turbot_local_directory_user.go
  turbot/resource_turbot_resource.go
  turbot/resource_turbot_saml_directory.go
  turbot/resource_turbot_turbot_directory.go
  turbot/resource_turbot_turbot_directory_test.go
Labels: size/S

#42 Remove tags from read operations
  turbot/resource_turbot_google_directory.go
  turbot/resource_turbot_local_directory.go
  turbot/resource_turbot_turbot_directory.go
  turbot/resource_turbot_turbot_directory_test.go
Labels: size/XS

#44 v1.3.1
  CHANGELOG.md
Labels: size/XS

#46 fix tags in read operation of resources
  apiClient/types.go
  turbot/resource_turbot_folder.go
  turbot/resource_turbot_google_directory.go
  turbot/resource_turbot_local_directory.go
  turbot/resource_turbot_local_directory_user.go
  turbot/resource_turbot_resource.go
  turbot/resource_turbot_saml_directory.go
  turbot/resource_turbot_turbot_directory.go
Labels: size/XS

#48 add new file resource
  CHANGELOG.md
  apiClient/queries.go
  apiClient/resource.go
  helpers/main.go
  turbot/provider.go
  turbot/resource_turbot_file.go
  turbot/resource_turbot_file_test.go
  website/docs/r/file.html.markdown
  website/docs/r/folder.html.markdown
  website/turbot.erb
Labels: documentation, size/XL

#49 Fix local & google directory tests to support tags. Closes #50
  turbot/resource_turbot_google_directory.go
  turbot/resource_turbot_google_directory_test.go
  turbot/resource_turbot_local_directory_test.go
  turbot/resource_turbot_shadow_resource_test.go
Labels: size/M

#45 [BUG]:turbot_saml_directory error when passing group_id_template. Closes #37
  apiClient/local_directory.go
  apiClient/queries.go
  apiClient/saml_directory.go
  turbot/resource_turbot_google_directory.go
  turbot/resource_turbot_local_directory.go
  turbot/resource_turbot_saml_directory.go
  website/docs/r/google_directory.html.markdown
  website/docs/r/saml_directory.html.markdown
Labels: documentation, size/XL

#52 v1.4.0. Closes #51
  CHANGELOG.md
Labels: size/XS

#55 [Fix]: GraphQL client failed to handle HTTP status codes. Closes #54
  go.mod
  go.sum
  turbot/provider.go
Labels: size/XS

#58 [Fix]: GraphQL client failed to handle HTTP status codes. Closes #54
  apiClient/client.go
  go.mod
  helpers/errors.go
Labels: size/XS

#60 v1.4.1 #59
  CHANGELOG.md
Labels: size/XS

#61 [Fix]: GraphQL client failed to handle HTTP status codes #54
  apiClient/client.go
  apiClient/errors.go
  helpers/errors.go
Labels: size/S

#64 v1.5.0. Closes #62
  CHANGELOG.md
Labels: size/XS

#65 [Feature]r/turbot_mod: add timeout block support, to handle creation of mods in environment. Closes #53
  turbot/resource_turbot_mod.go
  website/docs/r/mod.html.markdown
Labels: documentation, size/S

#68 v1.6.0 release notes. Closes #67
  CHANGELOG.md
Labels: size/XS

#33 Add new data source turbot_control
  apiClient/control.go
  apiClient/queries.go
  apiClient/types.go
  turbot/data_source_turbot_control.go
  turbot/data_source_turbot_control_test.go
  turbot/provider.go
  website/docs/d/control.html.markdown
  website/turbot.erb
Labels: documentation, size/L

#79 [BUG]r/turbot_profile: terraform plan shows a update/diff on profile argument after first successful run. Closes #78
  apiClient/profile.go
  apiClient/types.go
  turbot/resource_turbot_profile.go
  turbot/resource_turbot_profile_test.go
  website/docs/r/profile.html.markdown
Labels: documentation, size/M

#81 [Docs]: Fix docs for turbot_control. Closes #80
  website/docs/d/control.html.markdown
Labels: documentation, size/XS

#77 [BUG]r/turbot_google_directory: hosted_name argument always show a update on successful creation of resource. Closes #75
  apiClient/google_directory.go
  apiClient/queries.go
  apiClient/types.go
  turbot/resource_turbot_google_directory.go
  turbot/resource_turbot_google_directory_test.go
  website/docs/r/google_directory.html.markdown
Labels: documentation, size/M
