Repository turbot/terraform-provider-turbot, pull requests merged in 2020-05, with the labels that each got.

#7 Update directory resources to add new GraphQL mutations and support legacy ones #5
  apiClient/folder.go
  apiClient/google_directory.go
  apiClient/local_directory.go
  apiClient/local_directory_user.go
  apiClient/queries.go
  apiClient/saml_directory.go
  turbot/resource_turbot_google_directory.go
  turbot/resource_turbot_grant_activation_test.go
  turbot/resource_turbot_grant_test.go
  turbot/resource_turbot_local_directory.go
  turbot/resource_turbot_local_directory_user_test.go
  turbot/resource_turbot_profile_test.go
  turbot/resource_turbot_saml_directory.go
  turbot/resource_turbot_saml_directory_test.go
Labels: size/XL

#6 website: fix broken link in nav sidebar
  website/turbot.erb
Labels: documentation, size/XS

#2 Add new resource turbot_turbot_directory
  apiClient/queries.go
  apiClient/turbot_directory.go
  apiClient/types.go
  turbot/provider.go
  turbot/resource_turbot_turbot_directory.go
  turbot/resource_turbot_turbot_directory_test.go
  website/docs/index.html.markdown
  website/docs/r/turbot_directory.html.markdown
  website/turbot.erb
Labels: documentation, size/XL

#14 [BUG]: r/turbot_resource update resource failed with Data validation error
  apiClient/client.go
  apiClient/queries.go
  apiClient/types.go
  helpers/helpers_test.go
  helpers/main.go
  turbot/resource_turbot_resource.go
  turbot/resource_turbot_resource_test.go
Labels: size/XL

#10 r/turbot_saml_directory add allowGroupSyncing, profileGroupsAttribute, groupFilter as optional properties
  apiClient/saml_directory.go
  apiClient/types.go
  turbot/resource_turbot_saml_directory.go
  turbot/resource_turbot_saml_directory_test.go
  website/docs/r/saml_directory.html.markdown
Labels: documentation, enhancement, size/M

#16 v1.2.0
  CHANGELOG.md
  website/turbot.erb
Labels: documentation, size/XS

#18 add -parallel flag to reduce parallel execution of acceptance tests
  CHANGELOG.md
  GNUmakefile
  helpers/helpers_test.go
Labels: size/XS

#20 r/turbot_shadow_resource: add timeout in resource schema so we respect it over default timeout from resource
  turbot/resource_turbot_shadow_resource.go
  turbot/resource_turbot_shadow_resource_test.go
  website/docs/r/shadow_resource.html.markdown
Labels: documentation, size/M

#23 Add import checks in resources, fix read calls of resources to support terraform import
  turbot/resource_turbot_folder_test.go
  turbot/resource_turbot_google_directory.go
  turbot/resource_turbot_google_directory_test.go
  turbot/resource_turbot_grant_activation_test.go
  turbot/resource_turbot_grant_test.go
  turbot/resource_turbot_local_directory.go
  turbot/resource_turbot_local_directory_test.go
  turbot/resource_turbot_local_directory_user.go
  turbot/resource_turbot_local_directory_user_test.go
  turbot/resource_turbot_mod_test.go
  turbot/resource_turbot_saml_directory.go
  turbot/resource_turbot_saml_directory_test.go
  turbot/resource_turbot_smart_folder.go
  turbot/resource_turbot_smart_folder_test.go
  turbot/resource_turbot_turbot_directory.go
  turbot/resource_turbot_turbot_directory_test.go
Labels: size/M

#21 [BUG]: r/turbot_smart_folder_attachment import forces new resource creation
  turbot/resource_turbot_smart_folder_attachment.go
Labels: size/XS

#12 Update turbot_policy_setting to support passing an array of input queries for templateInput.
  apiClient/types.go
  helpers/utils.go
  turbot/resource_turbot_policy_setting.go
  turbot/resource_turbot_policy_setting_test.go
  website/docs/r/policy_setting.html.markdown
Labels: documentation, size/XL

#27 [BUG]r/turbot_smart_folder: Fix readSmartFolder query to fetch parentId
  apiClient/queries.go
  turbot/resource_turbot_smart_folder_test.go
Labels: size/XS

#28 v1.3.0
  CHANGELOG.md
  website/docs/r/policy_setting.html.markdown
Labels: documentation, size/XS
